name: todoe
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Pre-installed package from Flutter for icons
  cupertino_icons: ^0.1.3
  #Statemanagement package suggested from Flutter team
  provider: ^4.3.2+2
  #SQLite package for permanent storage
  sqflite: ^1.3.1+1
  #Package that it's used ONLY to change the status bar color
  #to transparent. Used ONLY on main.dart
  flutter_statusbarcolor: ^0.2.3
  #Firebase packages
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  google_sign_in: ^4.0.7
  #Time Picker

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: KumbhSans
      fonts:
        - asset: fonts/KumbhSans-Regular.ttf
        - asset: fonts/KumbhSans-Regular.ttf
        - asset: fonts/KumbhSans-Regular.ttf
  assets:
    - assets/